"""Add is_syncing

Revision ID: 20a2df29c5a5
Revises: drop_user_role_col
Create Date: 2026-06-20 15:58:13.524205
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a2df29c5a5'
down_revision: Union[str, None] = 'drop_user_role_col'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_readings', sa.Column('is_syncing', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_readings', 'is_syncing')
    # ### end Alembic commands ###
